= Restoring from Backup

. Make a directory for the restore
+
[source, bash]
----
mkdir /tmp/restore
----

. Restore from Cloud Files
+
You'll need to get the Cloud Files `username` and `apikey` from the existing Duplicity script (`/usr/local/bin/duplicity_performance_influxdb.rb`).
+
[source, bash]
----
export CLOUDFILES_USERNAME=<FIX_ME>
export CLOUDFILES_APIKEY=<FIX_ME>
export CLOUDFILES_REGION=DFW
duplicity --no-encryption restore cf+http://performance_influxdb /tmp/restore/
----

. Remove all the other backups and Decompress the restored files
+
[source, bash]
----
DATE_STAMP=??? # Value produced by $(date +%Y%m%d%H%M%S) for the desired backup
find /tmp/restore/ -type f ! -name "*.00_${DATE_STAMP}.gz" -delete
for file in /tmp/restore/*.00_${DATE_STAMP}.gz ; do
    gzip -d $file
    mv ${file%.gz} ${file%_$DATE_STAMP.gz}
done
----

. Restore the Metadata and the Performance database
+
[source, bash]
----
influxd restore -metadir /var/lib/influxdb/meta /tmp/restore
influxd restore -database performance -datadir /var/lib/influxdb/data /tmp/restore
----

. Delete the tmp files
+
[source, bash]
----
rm -rf /tmp/restore
----

. Do a Jig

= Restoring the Server

. Build a Debian Cloud Server
.. The "1 GB General Purpose v1" flavor is currently used
.. The hostname should be `influxdb.openrepose.org` (which can be set by naming the server the same) so that the Puppet master will apply the desired manifest
. Create a Cloud Block Storage volume
. Attach the new Cloud Block Storage volume to the new server
. Partition the new disk on the new server
.. Using `fdisk` is recommended
. Format the new partition on the new disk
.. Using `mkfs` is recommended
. Persist the volume mount
.. Edit the `/etc/fstab` file
. Mount the new volume
.. The volume should be mounted at the mount point referenced in the manifest (currently `/mnt/cbs`)
.. Using `mount -a` is recommended
. Connect the new server to the "ServiceNet" network
. Update the `influxdb.openrepose.org` DNS record to point to the IP address of the new server
. Run the Puppet agent on the new server after following the normal Puppet setup steps
