export HISTSIZE=10000
export JAVA_HOME=$(dirname "$(readlink -f $(which java))")/../..

alias proj="cd ~/dev/projects"
alias rep="cd ~/dev/projects/repose"

mkcd () { mkdir -p $1; cd $1; }

function clone {
  git clone git@github.com:rackerlabs/$1
}
